### ISSUE TITLE
Update documentation on README.md

### ISSUE THREAD

**Issue by mdee** [gevious/ember-datepicker#19]
Hello,

It looks like the README.md needs a quick update:

### outputFormat

`Type: String Default: YYYY-MM-DD`

This is the format in which the date is displayed in the input box.

After messing around with it for a bit it appears that the correct argument is simply 'format'

```html
{{date-picker date=dateArg format="MM-DD-YYYY" valueFormat="YYYY-MM-DD"}}
```

**Comment by jerel** [comment]
I had trouble getting this addon to work until I read the source and saw that `outputFormat` is never used.

`format` however [is specified](https://github.com/gevious/ember-datepicker/blob/master/addon/components/date-picker.js#L8) and works fine so I'm confused by your previous comment

**Comment by gevious** [comment]
Thanks. I had a closer look and you're right. Clearly I was confused somewhere. I've fixed the docs. Thanks all for your help

**Comment by jerel** [comment]
Awesome, and thanks for the nice add-on. I'm making good use of it :)
